### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by opoplawski** [mwilliamson/locket.py#3]
I'm trying to build an rpm package for locket and getting:
~~~~~
+ cd locket.py-0.2.0
+ nosetests-2.7
E..E.FF.F....
======================================================================
ERROR: tests.locket_tests.can_set_timeout_to_zero_to_raise_exception_if_lock_cannot_be_acquired
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/export/home/orion/redhat/python-locket-0.2.0/locket.py-0.2.0/tests/locket_tests.py", line 25, in run_test
    return func(lock_path)
  File "/export/home/orion/redhat/python-locket-0.2.0/locket.py-0.2.0/tests/locket_tests.py", line 173, in can_set_timeout_to_zero_to_raise_exception_if_lock_cannot_be_acquired
    locker_2.acquire()
  File "/export/home/orion/redhat/python-locket-0.2.0/locket.py-0.2.0/tests/locket_tests.py", line 251, in acquire
    self._process.stdin_write(b"\n")
  File "/usr/lib/python2.7/site-packages/spur/local.py", line 157, in stdin_write
    self._process_stdin.write(value)
IOError: [Errno 32] Broken pipe

======================================================================
ERROR: tests.locket_tests.error_is_raised_after_timeout_has_expired
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/export/home/orion/redhat/python-locket-0.2.0/locket.py-0.2.0/tests/locket_tests.py", line 25, in run_test
    return func(lock_path)
  File "/export/home/orion/redhat/python-locket-0.2.0/locket.py-0.2.0/tests/locket_tests.py", line 197, in error_is_raised_after_timeout_has_expired
    locker_2.acquire()
  File "/export/home/orion/redhat/python-locket-0.2.0/locket.py-0.2.0/tests/locket_tests.py", line 251, in acquire
    self._process.stdin_write(b"\n")
  File "/usr/lib/python2.7/site-packages/spur/local.py", line 157, in stdin_write
    self._process_stdin.write(value)
IOError: [Errno 32] Broken pipe

======================================================================
FAIL: tests.locket_tests.lock_file_blocks_until_lock_is_available
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/export/home/orion/redhat/python-locket-0.2.0/locket.py-0.2.0/tests/locket_tests.py", line 25, in run_test
    return func(lock_path)
  File "/export/home/orion/redhat/python-locket-0.2.0/locket.py-0.2.0/tests/locket_tests.py", line 125, in lock_file_blocks_until_lock_is_available
    assert locker_1.has_lock()
AssertionError

======================================================================
FAIL: tests.locket_tests.lock_is_acquired_if_available_before_timeout_expires
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/export/home/orion/redhat/python-locket-0.2.0/locket.py-0.2.0/tests/locket_tests.py", line 25, in run_test
    return func(lock_path)
  File "/export/home/orion/redhat/python-locket-0.2.0/locket.py-0.2.0/tests/locket_tests.py", line 224, in lock_is_acquired_if_available_before_timeout_expires
    assert locker_1.has_lock()
AssertionError

======================================================================
FAIL: tests.locket_tests.lock_is_released_if_holding_process_is_brutally_killed
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/export/home/orion/redhat/python-locket-0.2.0/locket.py-0.2.0/tests/locket_tests.py", line 25, in run_test
    return func(lock_path)
  File "/export/home/orion/redhat/python-locket-0.2.0/locket.py-0.2.0/tests/locket_tests.py", line 154, in lock_is_released_if_holding_process_is_brutally_killed
    assert locker_1.has_lock()
AssertionError

----------------------------------------------------------------------
Ran 13 tests in 0.952s

FAILED (errors=2, failures=3)
~~~~~

**Comment by mwilliamson** [comment]
Thanks for the bug report. I get all tests passing when I try it out locally, and I'm not sure what the cause of the failures is -- are you happy to try debugging those errors yourself?

**Comment by opoplawski** [comment]
I'm really not sure where to start debugging this.  I'm setting:

export LANG=en_US.UTF-8

**Comment by mwilliamson** [comment]
The broken pipe would suggest that the process is dead. Working out why it's died unexpectedly would probably be a good place to start.

**Comment by opoplawski** [comment]
Figured it out - needed to point PYTHONPATH to the installed location.
